version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: coupon-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: coupon_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: coupon-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data: